<?php
/**
 * @var $block Yotpo
 * @var Magento\Framework\Escaper $escaper
 */

use Yotpo\Reviews\Block\Yotpo;

$escaper = $escaper ?? $block;
?>
<?php if (!$block->isEnabled()) {
    return;
}
// phpcs:disable
?>
<!-- Yotpo - Add body class -->
<script>
    (function(){require(["jquery"],function($){$(document).ready(function() {$('body').addClass('yotpo-yotpo-is-enabled');});});})();
</script>
<!--/ Yotpo - Add body class -->
<!-- Yotpo - Widget Script -->
<script>
    (function e(){var e=document.createElement("script");e.type="text/javascript",e.async=true,e.src="<?= $escaper->escapeUrl($block->getYotpoWidgetUrl()) ?>";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})();
</script>
<!--/ Yotpo - Widget Script -->
<?php // phpcs:enable
